name: Run integration tests

on:
  workflow_dispatch:
    inputs:
      media_id:
        description: 'Media ID'
        required: true
        default: 'vi77Dgk0F8eLwaFOtC5870yn'
      playback_timeout_s:
        description: 'Playback timeout in seconds'
        required: true
        default: 60

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    strategy:
      matrix:
        api-level: [ 34 ]
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          disable-animations: true
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back emulated -camera-front emulated -gpu swiftshader_indirect
          script: |
            adb logcat -c
            adb logcat -s Agent:D TestRunner:D ExoPlayerAnalyticsAgentTest:D &
            ./gradlew player-analytics-exoplayer:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=video.api.player.analytics.exoplayer.ApiVideoExoPlayerAnalyticsListenerTest -Pandroid.testInstrumentationRunnerArguments.INTEGRATION_MEDIA_ID=$INTEGRATION_MEDIA_ID -Pandroid.testInstrumentationRunnerArguments.INTEGRATION_PLAYBACK_TIMEOUT_S=$INTEGRATION_PLAYBACK_TIMEOUT_S
        env:
          INTEGRATION_MEDIA_ID: ${{ github.event.inputs.media_id }}
          INTEGRATION_PLAYBACK_TIMEOUT_S: ${{ github.event.inputs.playback_timeout_s }}
      - name: Upload test reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'